"""message reports and user blocks

Revision ID: 8302730dd7cf
Revises: a94fc4ea71e2
Create Date: 2026-06-05 15:17:46.871945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8302730dd7cf'
down_revision: Union[str, Sequence[str], None] = 'a94fc4ea71e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('blocker_id != blocked_id', name='ck_user_blocks_different_users'),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_blocks_blocked_id'), ['blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_blocks_blocker_id'), ['blocker_id'], unique=False)

    op.create_table('message_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('target_message_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('SPAM', 'HARASSMENT', 'SCAM', 'HATE', 'NUDITY', 'OTHER', name='messagereportcategory'), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'DISMISSED', 'UPHELD', name='messagereportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('message_excerpt', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reports_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reports_status'), ['status'], unique=False)
        batch_op.create_index('ix_message_reports_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reports_target_message_id'), ['target_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reports_target_user_id'), ['target_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reports_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_reports_target_message_id'))
        batch_op.drop_index('ix_message_reports_status_created_at')
        batch_op.drop_index(batch_op.f('ix_message_reports_status'))
        batch_op.drop_index(batch_op.f('ix_message_reports_reviewed_by_id'))
        batch_op.drop_index(batch_op.f('ix_message_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_message_reports_id'))
        batch_op.drop_index(batch_op.f('ix_message_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_message_reports_category'))

    op.drop_table('message_reports')
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocked_id'))

    op.drop_table('user_blocks')
    # ### end Alembic commands ###
