"""initial schema

Revision ID: a94fc4ea71e2
Revises:
Create Date: 2026-05-27 03:42:21.815126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94fc4ea71e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_verification_token'), ['verification_token'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_1_id', sa.Uuid(), nullable=False),
    sa.Column('user_2_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('user_1_id != user_2_id', name='ck_conversations_different_users'),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_1_id', 'user_2_id', name='uq_conversations_users')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_1_id'), ['user_1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_2_id'), ['user_2_id'], unique=False)

    op.create_table('listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('ELECTRONICS', 'TEXTBOOKS', 'FURNITURE', 'DORM', 'APPLIANCES', 'CLOTHING', 'SHOES', 'ACCESSORIES', 'BIKES', 'SPORTS', 'TOOLS', 'OFFICE', 'MUSIC', 'MUSICAL_INSTRUMENTS', 'GAMES', 'COLLECTIBLES', 'ART', 'BABY', 'PET_SUPPLIES', 'TICKETS', 'SERVICES', 'OTHER', name='category'), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', 'POOR', name='condition'), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_seller_id'), ['seller_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('support_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticket_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('admin_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('target_listing_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.Enum('STRIKE', 'BAN', 'LISTING_REMOVAL', 'FLAG', name='adminactiontype'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_target_listing_id'), ['target_listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ai_conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='aimessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_ai_conversation_id'), ['ai_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_messages_id'), ['id'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'url', name='uq_images_listing_url')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_listing_id'), ['listing_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_listing_id'))
        batch_op.drop_index(batch_op.f('ix_images_id'))

    op.drop_table('images')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_id'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_messages_ai_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_target_listing_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_action_type'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_email'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_seller_id'))
        batch_op.drop_index(batch_op.f('ix_listings_is_active'))
        batch_op.drop_index(batch_op.f('ix_listings_id'))
        batch_op.drop_index(batch_op.f('ix_listings_category'))

    op.drop_table('listings')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_2_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_user_1_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verification_token'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
